#!/usr/bin/env python3
"""Render the repository artwork as terminal ASCII art and emit it as a C header.

Usage: ascii_logo.py [source.png]

Two kinds of source have to work. A stipple portrait is near-black ground with white dots,
where averaging a block gives a coverage fraction. A cut-out photograph is a dark subject on
transparency, where the alpha channel is the mask and luminance runs the other way. Polarity
is measured rather than assumed: whichever way the opaque pixels lean, the subject gets the
dense glyphs and the ground gets blanks.

Terminal cells are about twice as tall as they are wide, so the caller's column count is
paired with roughly half as many rows.
"""
import sys
from pathlib import Path

from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parent.parent
RAMP = " .:-=+*#%@"
SIZES = {"OIZYS_LOGO_LARGE": (44, 24), "OIZYS_LOGO_SMALL": (24, 13)}
DEFAULT = "Assets/tiny_Logo.png"


def prepare(path):
    """Return a greyscale image plus an alpha mask, both at full resolution."""
    image = Image.open(path)
    if image.mode != "RGBA":
        image = image.convert("RGBA")
    alpha = image.getchannel("A")
    # Composite onto mid grey so a white ground and a black ground both keep their contrast.
    ground = Image.new("RGBA", image.size, (128, 128, 128, 255))
    return Image.alpha_composite(ground, image).convert("L"), alpha


def render(grey, alpha, columns, rows):
    # Stretch the subject's own tonal range before quantising. Black hair against a light
    # ground otherwise saturates the top of the ramp and swallows the face entirely.
    shrunk = ImageOps.autocontrast(grey.resize((columns, rows), Image.LANCZOS), cutoff=5)
    small = shrunk.load()
    mask = alpha.resize((columns, rows), Image.LANCZOS).load()

    opaque = [small[x, y] for y in range(rows) for x in range(columns) if mask[x, y] > 128]
    if not opaque:
        opaque = [small[x, y] for y in range(rows) for x in range(columns)]
    lo, hi = min(opaque), max(opaque)
    span = max(1, hi - lo)
    # Polarity comes from the ground, not the average. Sampling the outer ring says which end
    # of the ramp is empty space: a light border means dark ink on paper and wants inverting,
    # a dark border means a bright subject on black and does not. Using the mean instead turns
    # a mostly-black stipple into a solid block of the heaviest character.
    border = [small[x, y] for y in range(rows) for x in range(columns)
              if (x < 1 or y < 1 or x >= columns - 1 or y >= rows - 1) and mask[x, y] > 128]
    invert = (sum(border) / len(border)) > 128 if border else False

    lines = []
    for y in range(rows):
        line = []
        for x in range(columns):
            if mask[x, y] <= 128:
                line.append(" ")
                continue
            level = (min(hi, max(lo, small[x, y])) - lo) / span
            if invert:
                level = 1.0 - level
            line.append(RAMP[min(len(RAMP) - 1, int(level * len(RAMP)))])
        lines.append("".join(line).rstrip())
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    return lines


def emit(handle, name, lines):
    handle.write(f"static const char *const {name}[] = {{\n")
    for line in lines:
        escaped = line.replace("\\", "\\\\").replace('"', '\\"')
        handle.write(f'    "{escaped}",\n')
    handle.write("};\n\n")


def main(argv):
    source = Path(argv[1]) if len(argv) > 1 else ROOT / DEFAULT
    grey, alpha = prepare(source)
    header = ROOT / "Sources" / "oizys" / "logo.h"
    with header.open("w") as handle:
        handle.write(f"/* Generated by Tools/ascii_logo.py from {source.name}. Do not edit by hand. */\n")
        handle.write("#ifndef OIZYS_LOGO_H\n#define OIZYS_LOGO_H\n\n")
        for name, (columns, rows) in SIZES.items():
            emit(handle, name, render(grey, alpha, columns, rows))
        handle.write("#endif\n")
    for line in render(grey, alpha, *SIZES["OIZYS_LOGO_LARGE"]):
        print(line)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
